### ISSUE TITLE
Cursor is not visible in leftmost column

### ISSUE THREAD

**Issue by sp3d** [eyelash/xi-gtk#14]
I'm not sure if this is a xi-gtk or xi-editor bug, but it might just be a matter of xi-gtk wanting to allocate a bit of padding surrounding the text so there's room to draw the insertion cursor to the left of the leftmost column. There's probably some interaction between this and line numbering.

This may be best achieved through an interface like GtkTextView's [gtk_text_view_set_{top,bottom,left,right}_margin](https://developer.gnome.org/gtk3/stable/GtkTextView.html#gtk-text-view-set-left-margin) functions.

**Comment by eyelash** [comment]
This will be fixed as soon as line numbers are implemented.

**Comment by eyelash** [comment]
I added some padding (hardcoded to the width of one char for now) which is something I wanted to do for quite some time (convinced by TextMate) but the interaction of vertical padding with the fact that only a partial view of the document is displayed required some more thought.
