### ISSUE TITLE
Indicate file modification status

### ISSUE THREAD

**Issue by sp3d** [eyelash/xi-gtk#15]
It's handy to be able to tell if an open file has unsaved changes or not.

**Comment by eyelash** [comment]
I already have a local patch for that but it needs to be supported by the core first. Also show a dialog when trying to close the editor with unsaved changes.

**Comment by srujan** [comment]
It would be nice to have the editor retain changes in an unsaved file (without prompting) even when closing. However, editor should prompt for confirmation when individual file is being closed with unsaved changes.

**Comment by eyelash** [comment]
closing in favor of #25 (indication was done in f03405d1a9ee2d6617081ea7b4520346d771db1c)
