### ISSUE TITLE
auto-scroll

### ISSUE THREAD

**Issue by eyelash** [eyelash/xi-gtk#20]
When selecting text with the mouse the view should automatically scroll if the mouse is near the top or the bottom.

**Comment by sp3d** [comment]
What exactly does this behavior look like? I'd expect a text widget to scroll if I'm selecting text outside of the currently visible region, but I thought that behavior was already implemented.

**Comment by eyelash** [comment]
@sp3d oh wow I just realized it really is even though I never wrote a single line of code to support it and therefore just assumed it wouldn't work :see_no_evil:
