### ISSUE TITLE
Most recent clone did not find Pkg-config

### ISSUE THREAD

**Issue by kootenpv** [eyelash/xi-gtk#26]
Right when I try `meson ..` in the `build/` folder, it shows everything "ok" except for lacking pkg-config. 

What can we do about it?

On Arch Linux (using rustup, having installed xi-core)

**Comment by eyelash** [comment]
What exactly does the error message say?

**Comment by eyelash** [comment]
Do you have the `base-devel` group installed?

**Comment by kootenpv** [comment]
Sorry, indeed was trying it on the VM. Thanks for helping me with this unrelated bug to your package.

I was able to install it. I ran it, and I think it might not work on i3. Perhaps more dependencies there. It complained it could not spawn a proces. Maybe because I'm using gcc... I have no idea, but I assume this is too bare of a system for it to work :)

Thanks!

**Comment by eyelash** [comment]
Try running some other GTK+ apps (Gedit for example). If they work but xi-gtk doesn't then it's a bug.

Also make sure you can run the command `xi-core` without error.
