### ISSUE TITLE
is there a mac binary available?

### ISSUE THREAD

**Issue by markmark1** [eyelash/xi-gtk#31]
is there a mac binary available?

**Comment by eyelash** [comment]
Of xi-gtk? No there isn't. I wouldn't even know how to build it on macOS.

**Comment by markmark1** [comment]
Ok what about Xi mac

________________________________

**Comment by markmark1** [comment]
What's xi

________________________________

**Comment by eyelash** [comment]
I don't think there are any mac binaries available at all, but [xi-mac](https://github.com/google/xi-mac) can easily be built with Xcode. See also google/xi-editor#373
