### ISSUE TITLE
The distance between the baselines of two adjacent lines should all be the same

### ISSUE THREAD

**Issue by EFanZh** [eyelash/xi-gtk#35]
![xi-gtk](https://user-images.githubusercontent.com/2160692/31530550-f859f604-afa6-11e7-96f1-564816f96e6c.png)

As you can see, if a text lines contain Chinese characters, this line will appear at an awkward position.

I think the distance between the baselines of two adjacent lines should all be the same. Also, the text should align with line number on the baseline instead of the top position.

**Comment by eyelash** [comment]
Could you please post the content of that file here? What does it look like in Gedit?

**Comment by EFanZh** [comment]
The file contains following text:

```
123abc
123abc一二三
123abc
```

Gedit also does not position lines on the right position, but Visual Studio Code does.

**Comment by eyelash** [comment]
This seems to be a regression of 59e5c7c90a67af44b5ca876d745b7daea0261b90.
