### ISSUE TITLE
xi-gtk shows bizzare behavior in files with nearly or more than 2147483647 lines

### ISSUE THREAD

**Issue by mateon1** [eyelash/xi-gtk#45]
To reproduce:

1. Create a file with 2147483645 newlines, with `yes '' | head -2147483645 > newlines.txt`
2. Open the file in xi-gtk
A few things are broken already, when you scroll to the end with Ctrl+End, everything stops displaying, but if you do it with the scrollbar, everything seems fine.. somewhat.
3. Place the cursor at some line at around a couple billion lines
4. Press enter.
Note that the line numbers behave weirdly, right now a line was created with the same line number as the next one (the consequent line numbers were not incremented).
The same thing happens if you delete lines, the line numbers stay out of sync.
The scroll bar isn't broken yet.
5. Press enter once more, making the file exactly INT_MAX lines long.
The scroll bar disappears, and the view is moved to the beginning of the file. Scrolling with the mouse wheel is broken.
6. Press enter once more, the file is now INT_MAX+1 lines.
The line numbers disappear.
If you click inside the xi-gtk window, some line numbers reappear, but the behavior is extremely broken.

**Comment by eyelash** [comment]
I guess this could be fixed by consistently using 64 bit integers for everything.

**Comment by eyelash** [comment]
> 4. Press enter.
Note that the line numbers behave weirdly, right now a line was created with the same line number as the next one (the consequent line numbers were not incremented).
The same thing happens if you delete lines, the line numbers stay out of sync.

This has nothing to do with the number of newlines. It also happens with other documents. The current line number implementation is only a temporary solution until google/xi-editor#184 is fixed.

**Comment by eyelash** [comment]
Strangely enough, the [GPtrArray](https://developer.gnome.org/glib/stable/glib-Pointer-Arrays.html#GPtrArray) uses a `guint` type for the length, which is still 32 bit on 64 bit systems. I think I can still fix this bug, but it will need some careful thinking and making sure it still compiles on 32 bit systems.

**Comment by eyelash** [comment]
5e02fede9b240a69da4c7a7280443b0ddb2c48f0 should fix most of these issues.

**Comment by mateon1** [comment]
I can confirm all of these issues, apart from the line numbers becoming out of sync are fixed, so I'm closing this issue.
I'm surprised how easy this was to fix!
