### ISSUE TITLE
Incorrect tabulation when line contains non-ascii characters

### ISSUE THREAD

**Issue by mateon1** [eyelash/xi-gtk#47]
Reproduction steps:

1. Open xi-gtk
2. Type `a<tab>a`
3. In a new line, copy and paste a non-ascii character, like `æ` and press `<tab>a`

Observed behavior:

In the first line, the indent works as expected, inserting 3 spaces between the `a` characters.
In the second line, the indent now only adds 2 spaces, rather than 3. This causes a misalignment when creating tables, for example.
```
a   a
æ  a
```

Expected behavior:

Both `a` characters are aligned vertically
```
a   a
æ   a
```

**Comment by eyelash** [comment]
Can you put the following line in the file `~/.config/xi-gtk/preferences.xiconfig`
```
translate_tabs_to_spaces = false
```
and try again? Xi translates tabs to spaces by default. And could you please open an issue in the [xi-editor repo](https://github.com/google/xi-editor) for the case that translate_tabs_to_spaces is true?

**Comment by eyelash** [comment]
I'm closing this issue here as this needs to be fixed in the core.
