### ISSUE TITLE
Searching large files is slow.

### ISSUE THREAD

**Issue by Qwertie-** [eyelash/xi-gtk#49]
I opened a 1gb postgres dump and ran a search for "2035428" which is contained a few times in the file and xi-gtk took roughly 2 seconds (Not sure how to time this).

I ran the same search using `time grep 2035428 data.pgbk` and got the time
```
real	0m0.660s
user	0m0.528s
sys	0m0.131s
```

I'd be happy to retest with some better measurements for xi-gtk if anyone would like to help me with a better way to record it.

**Comment by eyelash** [comment]
Could you please open an issue in the [core repository](https://github.com/google/xi-editor/issues) for that? The search is performed by the core and not by the front-end.

**Comment by Qwertie-** [comment]
[Done](https://github.com/google/xi-editor/issues/504) Should this issue be closed then?

**Comment by eyelash** [comment]
> Should this issue be closed then?

Yes.
