### ISSUE TITLE
build xi-gtk - "Invalid version of dependency gtk+" ['>= 3.20.0'] found '3.18.9'

### ISSUE THREAD

**Issue by denegny** [eyelash/xi-gtk#50]
after `meson ..`

take 

``` sh
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gtk+-3.0 found: NO found '3.18.9' but need: '>= 3.20.0'

Meson encountered an error in file meson.build, line 20, column 0:
Invalid version of dependency, need 'gtk+-3.0' ['>= 3.20.0'] found '3.18.9'.
```

this version is critical for your application?

**Comment by eyelash** [comment]
GTK 3.20 was released in March 2016, so I think it is reasonable to use it. Please note that you will still be able to run xi-gtk on older systems by using flatpak.

**Comment by denegny** [comment]
thanks for the answer

**Comment by rscircus** [comment]
Having exactly the same error with the most recent LinuxMint version (Sylvia 18.3), while onboarding in xi-editor's issue: https://github.com/google/xi-editor/issues/444. I'll document a (non-mess) workaround as soon as I figured it out.

**Comment by rscircus** [comment]
So, according to the [forums](https://forums.linuxmint.com/viewtopic.php?t=255750) LinuxMint 18.3 was planned to run in `GTK+3.18` and LinuxMint 19 will be running on `GTK+3.22`. According to [their news](https://blog.linuxmint.com/?p=3509), LM 19 is "pre-alpha". And according [to this](https://blog.linuxmint.com/?p=3494): 

> Linux Mint 19 is estimated to be released around May/June 2018.

So, that's quite a while. Easiest solution appears to be:

```
sudo add-apt-repository ppa:jonathonf/gtk3.22
sudo apt-get update && sudo apt-get upgrade
```

**Comment by rscircus** [comment]
This was successful and resulted in:

```
0> meson ..                                                      ↻  ⎇ master ~/src/xi-gtk/build@elephantsdream
The Meson build system
Version: 0.40.1
Source dir: /home/rawland/src/xi-gtk
Build dir: /home/rawland/src/xi-gtk/build
Build type: native build
Project name: xi-gtk
Native c compiler: cc (gcc 5.4.0)
Native vala compiler: valac (valac 0.30.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gtk+-3.0 found: YES 3.22.28
Native dependency json-glib-1.0 found: YES 1.1.2
Native dependency gio-unix-2.0 found: YES 2.50.3
Library m found: YES
Configuring config.h using configuration
Library config found: YES
Native dependency glib-2.0 found: YES 2.50.3
WARNING: GLib compiled dependencies do not work reliably with 
the current version of GLib. See the following upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=774368
Configuring com.github.eyelash.xi-gtk.service using configuration
Build targets in project: 3
```

However, the following step (`ninja`) failed:

```
../src/EditView.vala:172.7-172.20: error: The name `focus_on_click' does not exist in the context of `Xi.EditView.button_press_event'
		if (focus_on_click && !has_focus) {
		    ^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

Let's see what the heck that means...

**Comment by eyelash** [comment]
[`focus_on_click`](https://valadoc.org/gtk+-3.0/Gtk.Widget.focus_on_click.html) was added in GTK+ 3.20. Maybe you need to update your GTK+ Vala bindings as well.

**Comment by rscircus** [comment]
Alright,

```
sudo add-apt-repository ppa:vala-team/ppa
sudo apt-get update && sudo apt-get upgrade
```

we achieved great success:
```
0> ninja                                                         ↻  ⎇ master ~/src/xi-gtk/build@elephantsdream
[16/16] Linking target xi-gtk
```

Finally...
![](https://i.imgur.com/XJyemeI.jpg)
