### ISSUE TITLE
line numbers do in fact work, but syntax highlight doesn't

### ISSUE THREAD

**Issue by vn971** [eyelash/xi-gtk#52]
Subj. Line numbers do work on latest master. (Readme says otherwise)

But I can't get syntax highlight to work. Tried editing files with proper extensions (like "md", "sh", "rs") and bash shebang.

Q: should syntax highlight work, was there a regression?

**Comment by eyelash** [comment]
Line numbers are only a temporary hack until google/xi-editor#184 is fixed (see also #45).
For syntax highlighting you need to install the syntect plugin which can be found [here](https://github.com/google/xi-editor/tree/master/rust/syntect-plugin). It needs to be installed to either `prefix/share/xi-gtk/plugins` or `~/.config/xi-gtk/plugins`. [Here](https://github.com/eyelash/xi-gtk/blob/4637e60801317824cc523f9e73aeb9409f501dee/com.github.eyelash.xi-gtk.json#L51) is an example script that installs the syntect plugin. You can also use the makefile that comes with the syntect plugin (like `make XI_PLUGIN_DIR=~/.config/xi-gtk/plugins install`).

**Comment by vn971** [comment]
Thanks! Clear.
