### ISSUE TITLE
Add "how to change background color" to README

### ISSUE THREAD

**Issue by Anton-4** [eyelash/xi-gtk#56]
First of all, thank you for this amazing project, it's very useful for working with large files like in Data Science.

How can I adjust the background and foreground(text) colors (can be a total hack for now)?
I've tried several things but could not get it to work.
It would be useful if this was added to the README.
I easily get headaches from the black-and-white contrast so custom colors would be really useful for me.

**Comment by eyelash** [comment]
There is experimental support for themes in xi-gtk. Try starting xi-gtk with `XI_THEME="Solarized (dark)" xi-gtk`. Please note however that the whole project is still very much experimental. xi-gtk is not yet ready to replace your favourite editor.

**Comment by Anton-4** [comment]
Thanks, that works! I agree about the documentation.
