### ISSUE TITLE
Syntax Highlighting Failure

### ISSUE THREAD

**Issue by infosisio** [eyelash/xi-gtk#61]
I would like to point out that there are no clear instructions on how to get syntax highlighting working.

I have tried to utilize the make file by redirecting it to the folder of xi and it seems to have been installed but some failure is reported in the logs (I don't have those messages around right now to report them)

Any plans to make it easy for users of popular distributions to install syntax highlighting?

Personally, I am on Ubuntu 18.10.

I would love to use xi as it's freedom respecting and super responsive.

Thanks a lot.

**Comment by eyelash** [comment]
Executing `make XI_CONFIG_DIR=~/.config/xi-gtk install` inside the `syntect-plugin` directory should make syntax highlighting work.
The longer term plan is to use Flatpak to produce a bundle that includes working syntax highlighting. You can find a preliminary manifest [here](https://github.com/eyelash/xi-gtk/blob/flatpak/com.github.eyelash.xi-gtk.json). Also, personally I'd like to see the syntax highlighting plugin moved inside the core binary but that decision is up to the developers of xi-core.
All that said, xi-gtk is still heavily work in progress and not yet meant to replace your favourite text editor.

**Comment by dessalines** [comment]
Same, I'd really like some way to enable this out of the box.

**Comment by eyelash** [comment]
@dessalines do the instructions I posted above work for you?

**Comment by eyelash** [comment]
I updated the README to include simple instructions on how to build a fully functional xi-gtk including syntax highlighting.
