### ISSUE TITLE
Can't unindent a chunk of code

### ISSUE THREAD

**Issue by OxyDeadbeef** [eyelash/xi-gtk#63]
When I select a chunk of code, I can press tab and it adds a tab to the beginning of all of the selected lines.  I like this feature, but there's no way to do the opposite.  Gedit does this as well, and also SHIFT + TAB removes a tab from the beginning of all the selected lines.  I think it would be useful if xi-gtk did the same thing.

**Comment by eyelash** [comment]
I believe xi-core has a command for this so it should be really easy to wire this up.
