### ISSUE TITLE
Unknown option --from-git= ...

### ISSUE THREAD

**Issue by drandreaskrueger** [eyelash/xi-gtk#66]
this http://tonsky.me/blog/disenchantment/ (scroll to bottom) made me curious, but:

### error message:

```
Option parsing failed: Unknown option --from-git=https://github.com/eyelash/xi-gtk.git
```

### reproduce:

Debian https://flatpak.org/setup/Debian/  
had to manually change it to `sudo apt install flatpak flatpak-builder`  

```
flatpak --version; flatpak-builder --version
Flatpak 0.8.9
Flatpak 0.8.9

flatpak-builder --from-git=https://github.com/eyelash/xi-gtk.git --install-deps-from=flathub --install ~/.xi-gtk-build flatpak.json
```

looks like the Debian included flatpak version is too old for your command?  How to upgrade? Thanks.

**Comment by eyelash** [comment]
Yes, it looks like your version of Flatpak is too old. There's a much newer version of Flatpak in the [Debian backports](https://backports.debian.org/Instructions/) repository.

**Comment by drandreaskrueger** [comment]
Thanks a lot! Yes, looking good:

I did this

```
sudo nano /etc/apt/sources.list.d/backports.list
         deb http://deb.debian.org/debian stretch-backports main
sudo apt update 
sudo apt -t stretch-backports install flatpak flatpak-builder
flatpak --version; flatpak-builder --version
```
> Flatpak 1.2.4   
> flatpak-builder 1.0.5   


in the end I got this
```
flatpak-builder --from-git=https://github.com/eyelash/xi-gtk.git --install-deps-from=flathub --install ~/.xi-gtk-build flatpak.json
...
error: Flatpak system operation ConfigureRemote not allowed for user
Install failed: Child process exited with code 1
```

so I redid it with sudo and force-clean
```
sudo flatpak-builder --force-clean --from-git=https://github.com/eyelash/xi-gtk.git --install-deps-from=flathub --install ~/.xi-gtk-build flatpak.json
```
was that right?

**Comment by eyelash** [comment]
> was that right? or is there a better way?

You shouldn't need sudo for running flatpak-builder but I'm not sure what happened here.

> small usability problem: I can just press X and it closes a file even if there were recent changes. One is not asked to save the file before exit.

There is #25 and xi-editor/xi-editor#913 for that.
