### ISSUE TITLE
Publish flatpak app

### ISSUE THREAD

**Issue by Mart-Bogdan** [eyelash/xi-gtk#67]
Why do I have to build it manualy via flatpack? Could you publish it as binary?

BTW it's downloading and build xi-core and rust, despite I've installed xi-core already in my system (

**Comment by eyelash** [comment]
xi-gtk is very much a work in progress. At this point it is only useful for developers and curious people and therefore I think it's okay that you have to build it from source.

> BTW it's downloading and build xi-core and rust, despite I've installed xi-core already in my system (

This is the way flatpak works: you include all dependencies (except for the runtime) inside the flatpak and therefore you can be sure your app always runs in the same configuration. (Imagine some breaking changes in xi-core. I could then build the flatpak with a specific version of xi-core that I know will work until xi-gtk is updated to work with a newer version of xi-core.)

**Comment by Mart-Bogdan** [comment]
Seems reasonable. Thanks for answer.
